#!/usr/bin/env bash
#
# https://github.com/cptMikky/hamster-dmenu
#

function default_menu() {
  if [ -n "$WAYLAND_DISPLAY" ]; then
    echo "wofi --dmenu"
  else
    echo "dmenu"
  fi
}

function defaults() {
  cat > $conf << EOF
hamster="hamster"
menu="$(default_menu)"
menu_prompt="current"
menu_prompt_text=""
menu_prompt_param="-p"
EOF
}

confhome=${XDG_CONFIG_HOME:-$HOME/.config/}
[ -d "$confhome" ] || confhome="$HOME/."
conf="${confhome}hamster-dmenu/hamster-dmenu.conf"
[ -f $conf ] || (mkdir -p $(dirname $conf); defaults)
source $conf

declare -A ham=(
  [list]="${hamster} activities"
  [start]="${hamster} start"
  [stop]="${hamster} stop"
  [current]="${hamster} current"
  [gui]="${hamster}"
)

entries=$(${ham[list]})

[ -n "$menu_prompt" ] && _p="$menu_prompt_param"

_pr=""
case "$menu_prompt" in
  current) 
    _pr="$(${ham[current]})"
    ;;
  custom)
    _pr="$menu_prompt_text"
    ;;
esac

activity=$(echo "${entries}" | ${menu} $_p "$_pr" "$@") || exit 0

case "${activity}" in
  -)
    ${ham[stop]}
    ;;
  /)
    ${ham[gui]}
    ;;
  *)
    ${ham[start]} "${activity}"
esac




